### ISSUE TITLE
Conn::tryReconn有一个mutex重入问题

### ISSUE THREAD

**Issue by 0x5143** [funny/snet#4]
tryReconn里会触调用`conn.Write`，同时会加`c.reconnMutex.Lock()`锁，而Write方法里会加
`c.reconnMutex.RLock()`，造成重入问题。

**Comment by bg5sbk** [comment]
你看错了吧，conn.Write不是snet的Write，是底层连接的Write

**Comment by 0x5143** [comment]
看样子，是我的用法不对。
